version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: aftas_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/aftas_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
